displayName: Auth Token Exchange Plugin

type: middleware
iconPath: .assets/icon.png

import: github.com/lifter-ai/auth-token-exchange-plugin

summary: A custom authentication plugin for Traefik that verifies tokens with a configurable users-api service and in case of success exchanges them for an internal token that comes from the response body to pass it downstream for context.

testData:
  authURL: "https://example.com/verify"  # This URL will be validated but not used with test token
  production: false
  headers:
    Authorization: Bearer test-token
